server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:

        # - id: google
        #   uri: https://www.google.com
        #   predicates:
        #     - Path=/google/**

        - id: account
          uri: http://account:8080
          predicates:
            - Path=/account/**

<<<<<<< HEAD
        - id: auth
          uri: http://auth:8080
          predicates:
            - Path=/auth/**

=======
>>>>>>> 259312bae3dcdbb10664d898b90c1ca149eef44b
        - id: product
          uri: http://product:8080
          predicates:
            - Path=/product/**

<<<<<<< HEAD
        - id: order
          uri: http://order:8080
          predicates:
              - Path=/order/**
=======
        - id: auth
          uri: http://auth:8080
          predicates:
            - Path=/auth/**

        - id: order
          uri: http://order:8080
          predicates:
            - Path=/order/**
>>>>>>> 259312bae3dcdbb10664d898b90c1ca149eef44b

        # - id: exchange
        #   uri: http://exchange:80
        #   predicates:
        #     - Path=/exchange/**

logging:
  level:
<<<<<<< HEAD
    store: ${LOGGING_LEVEL_STORE:debug}

management:
  endpoint:
      gateway:
        enabled: true
  endpoints:
      web:
        base-path: /gateway/actuator
        exposure:
            include: [ 'prometheus', 'gateway' ] 
=======
    store: ${LOGGING_LEVEL_STORE:debug}
>>>>>>> 259312bae3dcdbb10664d898b90c1ca149eef44b
